### ISSUE TITLE
Docker installation "Tutorial" link in README is broken

### ISSUE THREAD

**Issue by jsuhaas22** [lvgl/lv_port_texas_sk-am62p-lp#1]
In the [Install Docker](https://github.com/[lvgl/lv_port_texas_sk-am62p-lp](https://github.com/lvgl/lv_port_texas_sk-am62p-lp?tab=readme-ov-file#install-docker)?tab=readme-ov-file#install-docker) section, the "Tutorial" link is broken. 

It says "Page Not Found".

**Comment by kisvegabor** [comment]
Thank you! 
cc @EDGEMTech-GabrielC

**Comment by EDGEMTech-GabrielC** [comment]
Fixed

**Comment by jsuhaas22** [comment]
Great, thanks!
